### ISSUE TITLE
Correct licensing?

### ISSUE THREAD

**Issue by gmponos** [webthinkgr/codesniffer#1]

**Comment by gmponos** [comment]
@wimg @jrfnl maybe you could advise me here if you have some time.

-  @wimg the package of yours says [inside](https://github.com/wimg/PHPCompatibility/blob/master/Sniffs/PHP/DeprecatedNewReferenceSniff.php#L10) that it uses `2012 Cu.be Solutions bvba` but on the readme it says that it uses `GNU LESSER GENERAL PUBLIC LICENSE`. Are the copyright a different thing from the license?
- @wimg You have a sniff about [RemovedFunctions](https://github.com/wimg/PHPCompatibility/blob/master/Sniffs/PHP/RemovedFunctionParametersSniff.php). As you can see I changed it to [this](https://github.com/webthinkgr/codesniffer/blob/master/Webthink/Sniffs/PHP7/RemovedFunctionsSniff.php). As you may see the two codes have nothing to do with each other. Your sniff was just the inspiration of creating my sniff.
   - So since you created the sniff first are you the only one allowed to use a sniff called `PHP7RemovedFunctions`?
   - I really thought that by mentioning that you were the inspiration over this that it would be a good thing. The truth is that for this certain sniff (and maybe in many more) I could have avoided mentioning that your package was the inspiration and based by the code no-one would have noticed it.
   - Aren't all developers inpired by other all the time?
- I still do not understand what the problem is? I am not allowed to copy code from other packages that use a Public Lic or I am allowed and I missed some crucial info?
   - If it is the second can you advise me accordingly?
   - If it is the first one for instance LGPLv3 i think it says that I can modify copies. Isn't it?

Thank you for your time.

**Comment by wimg** [comment]
To answer your questions :
- There is indeed a difference between copyrights and license. Copyrights exist automatically as soon as code (or an article, a book, etc.) is written. They remain with the code, even if the code is modified extensively. This means that if a piece of code is copied, the copyrights on that piece of code still apply and therefor must be mentioned.
- The way the software is distributed, can be used, modified, etc - as well as all the things that must or can not be done, is defined in the license. For PHPCompatibility, the license is the LGPL. You can read the full text of it, but I find this easier as a reference : https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)
- The name of the sniff is most certainly not copyrightable... it would be very bad if only 1 person could create a file called index.php ;-)
- LGPL indeed says you can make copies, but that refers to a copy of the full software, not bits and pieces of it.
- Let me be clear : every open source developer loves to see their software being used. But there's a few things that can be improved to what you did :
1. By copying code, you will never benefit from any improvements, bugfixes, etc. - and if you make improvements or bugfixes, the library you copied from will not benefit from it either. Including the library is always the better choice
2. You did mention that you based it on other code, but you left out the copyright and at the same time you must then also release your work under the same license

You might believe we're nitpicking. The things is we've been doing this for a while and we know where it can lead. We feel it's better to advise people on what they're doing wrong and why so that everyone will happily continue to contribute to open source and, as you say, be inspired by other developers. The best way to show that you were inspired is by respecting the developers by keeping the copyrights and license intact.

**Comment by gmponos** [comment]
> and if you make improvements or bugfixes, the library you copied from will not benefit from it either.

I am not gonna see a bug and not commit a PR. `https://github.com/aik099/CodingStandard/pull/100` (although this is open because i forgot it but I have also some others)

> By copying code, you will never benefit from any improvements, bugfixes, etc. - 

I was willing to live with this. For instance coder of drupal has a sniff that checks that the last element of array has a comma but it does a lot more checks. I removed all the rest checks in order to have performance benefits for my Continues Integration.

I know what is the general concept that you tried to pass on 1 & 2 but I just considered the benefits and misbenefits of including the whole libraries and created a new lib.

**Comment by wimg** [comment]
You are free to pass on the benefits, but please respect the developers of the original code by keeping their copyrights intact and ofcourse, for legal reasons, obey the respective license (which is almost impossible if you use code from different projects since the licenses will conflict).

**Comment by gmponos** [comment]
OK to the practical part. Is something like this fine?

https://github.com/webthinkgr/codesniffer/blob/1e20e602af848371d0446edc3812f3ffd5c39d3b/Webthink/Sniffs/PHP7/RemovedGlobalVariablesSniff.php

**Comment by jrfnl** [comment]
> Is something like this fine?

No, it is not.

As @wimg stated before:
> LGPL indeed says you can make copies, but that refers to a copy of the full software, not bits and pieces of it.

**Comment by gmponos** [comment]
FYI as I said before if I tried 10 times to develop a sniff about the [NoElseIf](https://github.com/webthinkgr/codesniffer/blob/2.x/src/Webthink/Sniffs/ControlStructures/NoElseSniff.php) most probably I would end up in the same result.

So at the end I see more trouble caused from mentioning the guy who originally gave me the idea about writing a sniff for NoElseIf.

So I was just wondering.. have you thought that maybe with all this attitude you are pushing people away from mentioning that other guy?

**Comment by gmponos** [comment]
FYI

https://irc.cakephp.org/

```
# 	Yesterday, 21:21 	savant 	licensing is a strange beast :(
# 	Yesterday, 21:20 	savant 	it just helps protect us if there are lawsuits against the cakephp org
# 	Yesterday, 21:20 	savant 	i mean, we're not going to go after you or anything
# 	Yesterday, 21:20 	gmponos 	thank you
# 	Yesterday, 21:20 	savant 	yea
# 	Yesterday, 21:20 	gmponos 	ok so if I just include the Header part that you put in all CakePHP file I am fine?
# 	Yesterday, 21:19 	savant 	generally when doing that with OSS, if it has a license at the top, you just include that
# 	Yesterday, 21:19 	savant 	did you copy/paste the file
# 	Yesterday, 21:19 	gmponos 	I am really unaware if I did something wrong here...
# 	Yesterday, 21:19 	gmponos 	are there any more info that Should be included?
# 	Yesterday, 21:19 	gmponos 	I mean about the licensing part
# 	Yesterday, 21:18 	gmponos 	hello is there a problem with this https://github.com/webthinkgr/codesniffer/blob/master/Webthink/Sniffs/Formatting/UseInAlphabeticalOrderSniff.php
```

**Comment by gmponos** [comment]
I am little confused right now.

I was going through the projects that I used their sniffs and I saw this:

https://github.com/php-fig-rectified/psr2r-sniffer/blob/master/PSR2R/Sniffs/ControlStructures/ConditionalExpressionOrderSniff.php
https://github.com/php-fig-rectified/psr2r-sniffer/blob/master/PSR2R/Sniffs/ControlStructures/ElseIfDeclarationSniff.php

From what I know  @dereuromark is a very active OSS so I don't think he does not know what he is doing.

> LGPL indeed says you can make copies, but that refers to a copy of the full software, not bits and pieces of it.

Is this applicable only for the LGPLv3 and the GNU licenses generally?

**Comment by gmponos** [comment]
From what I undrestand MIT and BSD can be sublicensed.

@aik099 - uses BSD (which I can see it can be sublicensed)
@klausi  (drupal/coder) - Sorry but I don't see a license
@cakephp - They don't seem to have a problem and they use the MIT license.
@TomasVotruba (object callisthenics) - uses the MIT license (which I can see it can be sublicensed)
mediawiki - only one sniff I will use @dereuromark one instead.

So I will just remove yours sniffs and rewrite them from scratch.

**Comment by TomasVotruba** [comment]
For me, as long as you find my code helpful, use it as you need :+1: Also you can remove my emails and @author reference. They make code less readable with no added value.

**Comment by dereuromark** [comment]
@gmponos You need to add a license file to your root, and also note the license (I recommend MIT) noted in your composer.json and ideally also in your files at the top.
This way other people are allowed to also re-use your sniffs and code.

**Comment by gmponos** [comment]
Generally with all this issue created I am thinking of [this](http://www.wtfpl.net/) 😋 

I will add the MIT though :D

**Comment by TomasVotruba** [comment]
@dereuromark File level license have also no added value, just make code unreadable. All you really need is package level `LICENSE`. 

Also, having more places increase change that sb forgets to add or update license in every place is used - composer has one, file has 2, LICENSE has another one... And if care, this is a mess.

Better done than perfect.

**Comment by TomasVotruba** [comment]
@gmponos Exactly :laughing:

**Comment by klausi** [comment]
drupal/coder is GPLv2.

**Comment by gmponos** [comment]
Haha... this becomes confusing even more... 

https://github.com/klausi/coder/blob/8.x-2.x/coder_sniffer/Drupal/Sniffs/Formatting/MultiLineAssignmentSniff.php#L22

So a GPLv2 (maybe generally GPL*) can have a BSD/MIT per file?

**Comment by gmponos** [comment]
Anyway @klausi do you have any objection with the current package (some sniffs that I used from you) as long as I correct the headers and mention your package as the original source?

**Comment by klausi** [comment]
Hehe, yes, some sniffs in Coder have been copied from PHPCS itself, that's why there are headers in there.

I'm fine to relicense any sniff I wrote in Coder under the MIT license you are using here. Note that this is not possible automatically because GPL is a copyleft license and MIT is not. To relicense GPL code under MIT you need to ask all copyright holders (all contributors) to get permission to relicense under MIT. So whatever you copy from Coder please check if there were other contributors that you need to ask to relicense under MIT.

The other possibility is that you license your package as GPL, then that is compatible automatically.

**Comment by gmponos** [comment]
> The other possibility is that you license your package as GPL, then that is compatible automatically.

> Good, so remove any ripped sniffs from your repo. Include the original repos as dependencies instead.
Submit PRs to the original repos for any improvements you may have made.

So there alternative solutions rather than the one suggested by @jrfnl nice. That is what I wanted to clear out.

**Comment by TomasVotruba** [comment]
@klausi Hey, just wondering, why copy and not use 3rd party working code (if not dead :))?

Personally I prefer to outsource responsibility and work with maintaining and testing a code that does the same think as mine:

- https://github.com/Symplify/Symplify/pull/143/commits/c72d51c7538c5492ecfeefc78f49a807811587a0
- https://github.com/Symplify/Symplify/pull/143/commits/063ebb77090b62f14db243a36ef6b839fbbf958e

Etc.

**Comment by wimg** [comment]
You can use GPL license and incorporate LGPL licensed content, however you must retain copyright statements on any files being used.
Still, what you're creating is a set of sniffs that will quickly be out-of-date. You'll have to maintain things all the time, while you could just reuse sniffs from existing projects instead. But I guess that's your call...

**Comment by klausi** [comment]
@TomasVotruba because we had to modify the upstream sniffs from PHPCS because they didn't fit exactly.

**Comment by TomasVotruba** [comment]
@klausi In what way they didn't fit? There might be better solution for that, cause I had similar problem with few sniffs.

**Comment by klausi** [comment]
@TomasVotruba that depends on the sniff, usually there is a comment like "Largely copied from Squiz_Sniffs_Commenting_PostStatementCommentSniff but we want the fixer to move the comment to the previous line."

**Comment by TomasVotruba** [comment]
@klausi Yea, I know comments detection or position are one of main issues with CodeSniffer. I had to done one custom `ClassSniff` before myself.

Let's continue in new issue, this is different topic... https://github.com/webthinkgr/codesniffer/issues/3
