### ISSUE TITLE
Tip for outsourced sniffs with the same features (saves work, time and kittens!)

### ISSUE THREAD

**Issue by TomasVotruba** [webthinkgr/codesniffer#3]
Just a tip to outsource few sniffs that might save you some work. Don't mean to pry.

I saw you added warnings in some fork. From my experience, it's like telling people to write test without having CI. It will be ignored in time. Having errors with more free limits is way better.

https://github.com/webthinkgr/codesniffer/blob/master/Webthink/Sniffs/Array/LastElementCommaSniff.php
=> https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/ArrayNotation/TrailingCommaInMultilineArrayFixer.php

https://github.com/webthinkgr/codesniffer/blob/master/Webthink/Sniffs/WhiteSpace/OpenTagNewLineSniff.php => https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php

https://github.com/webthinkgr/codesniffer/blob/master/Webthink/Sniffs/Formatting/UseInAlphabeticalOrderSniff.php => https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/Namespaces/AlphabeticallySortedUsesSniff.php

https://github.com/webthinkgr/codesniffer/blob/master/Webthink/Sniffs/NamingConventions/ValidInterfaceNameSniff.php => https://github.com/Symplify/CodingStandard/blob/master/src/Sniffs/Naming/InterfaceNameSniff.php

https://github.com/webthinkgr/codesniffer/blob/master/Webthink/Sniffs/Methods/OrderSniff.php => https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/ClassNotation/OrderedClassElementsFixer.php

https://github.com/webthinkgr/codesniffer/blob/master/Webthink/Sniffs/Commenting/VariableCommentSniff.php => https://github.com/Symplify/CodingStandard/blob/master/src/Sniffs/Commenting/VarPropertyCommentSniff.php + https://github.com/Symplify/CodingStandard/blob/master/src/Sniffs/Commenting/BlockPropertyCommentSniff.php

**Comment by gmponos** [comment]
There are various reasons why I chose to do so and not outsource.

1. First of all to exclude some of the rules you mention above I just wanted to show you this about the minimum versions that these packages require:

- [travis of slevomat](https://github.com/slevomat/coding-standard/blob/1.1.1/.travis.yml#L3)
- [travis of simplify](https://github.com/Symplify/CodingStandard/blob/v1.4.10/.travis.yml#L5)

2. To exclude more of the above rules that you mention I know that I could use PHP-CS-Fixer but I just wanted all the things in one place.

3. Then there is the performance issue.

Some of these rules are doing too much checks. I know that I can exclude the extra rules that I do not want per sniff/class. But I think in codesniffer the code still passes from all the checks and it just supruss them. You could argue about it and say _why do you care about performace for Codesniffer? etc etc._ Well it's complicated.

4. About maintainance.

Most of the sniffs I have there are not so complex. So there are not so many bugs that may occur.
As you may saw they are checking just for the basic stuff. So it's a once off maintenance. Also maintainance might depend also from the usage. I never and I do not expect this package to have some crazy number of developers using it in order to have extra requirements etc etc.

5. This was intented mainly for personal use.

When I started this package version 3.x of Codesniffer was already on the way. I expect that now most of the sniffs will start using it. This might make things simpler for various reasons.

6. On new version it will be easy to extend.

 - Codesniffer 3.x it's easier to have tests.
 - If you used composer some codesniffer libraries used to require to install them globally [Check this](https://github.com/wimg/PHPCompatibility#installation-via-a-git-check-out-to-an-arbitrary-directory-method-3). Generally it was painful. Now with the Namespacing I hope this will be fixed.

So it will give the developer the ability to do something like this:

```
class MySniff extends YourSniff {

}
```

And you will now be able to override classes and functions without a problem. That's one more way how you may solve any licensing issue 😋 

PS 

> I saw you added warnings in some fork. From my experience, it's like telling people to write test without having CI. It will be ignored in time. Having errors with more free limits is way better.

Most probably I am lost in translation. I didn't really catch that,.. You are talking about which warnings?

**Comment by TomasVotruba** [comment]
Thanks for sharing ideas.

As for performance, I'd love to see some numbers.

CodeSniffer is very, slow, matter the version. First run on huge project, 120 seconds. Second run? 120 seconds :)

PHP-CS-Fixer and EasyCodingStandard? Second run  under 3  secs. Why? They both use check only changes files. Simple and works.

I don't get the Travis part.

I'll try rephrase my last paragraph​:why do you need warnings and not just errors?
